/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TransportListRouteImport } from './routes/transport-list'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewTransportRouteImport } from './routes/new-transport'
import { Route as NewMemoRouteImport } from './routes/new-memo'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ConsigneesRouteImport } from './routes/consignees'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportIdRouteImport } from './routes/transport.$id'
import { Route as TransportEditIdRouteImport } from './routes/transport-edit.$id'
import { Route as MemoIdRouteImport } from './routes/memo.$id'
import { Route as ApiKeepaliveRouteImport } from './routes/api/keepalive'

const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportListRoute = TransportListRouteImport.update({
  id: '/transport-list',
  path: '/transport-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTransportRoute = NewTransportRouteImport.update({
  id: '/new-transport',
  path: '/new-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMemoRoute = NewMemoRouteImport.update({
  id: '/new-memo',
  path: '/new-memo',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsigneesRoute = ConsigneesRouteImport.update({
  id: '/consignees',
  path: '/consignees',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIdRoute = TransportIdRouteImport.update({
  id: '/transport/$id',
  path: '/transport/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportEditIdRoute = TransportEditIdRouteImport.update({
  id: '/transport-edit/$id',
  path: '/transport-edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoIdRoute = MemoIdRouteImport.update({
  id: '/memo/$id',
  path: '/memo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/consignees': typeof ConsigneesRoute
  '/fleet': typeof FleetRoute
  '/new-memo': typeof NewMemoRoute
  '/new-transport': typeof NewTransportRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transport-list': typeof TransportListRoute
  '/trash': typeof TrashRoute
  '/user-management': typeof UserManagementRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/memo/$id': typeof MemoIdRoute
  '/transport-edit/$id': typeof TransportEditIdRoute
  '/transport/$id': typeof TransportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/consignees': typeof ConsigneesRoute
  '/fleet': typeof FleetRoute
  '/new-memo': typeof NewMemoRoute
  '/new-transport': typeof NewTransportRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transport-list': typeof TransportListRoute
  '/trash': typeof TrashRoute
  '/user-management': typeof UserManagementRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/memo/$id': typeof MemoIdRoute
  '/transport-edit/$id': typeof TransportEditIdRoute
  '/transport/$id': typeof TransportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/consignees': typeof ConsigneesRoute
  '/fleet': typeof FleetRoute
  '/new-memo': typeof NewMemoRoute
  '/new-transport': typeof NewTransportRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transport-list': typeof TransportListRoute
  '/trash': typeof TrashRoute
  '/user-management': typeof UserManagementRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/memo/$id': typeof MemoIdRoute
  '/transport-edit/$id': typeof TransportEditIdRoute
  '/transport/$id': typeof TransportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/consignees'
    | '/fleet'
    | '/new-memo'
    | '/new-transport'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transport-list'
    | '/trash'
    | '/user-management'
    | '/api/keepalive'
    | '/memo/$id'
    | '/transport-edit/$id'
    | '/transport/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/consignees'
    | '/fleet'
    | '/new-memo'
    | '/new-transport'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transport-list'
    | '/trash'
    | '/user-management'
    | '/api/keepalive'
    | '/memo/$id'
    | '/transport-edit/$id'
    | '/transport/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/consignees'
    | '/fleet'
    | '/new-memo'
    | '/new-transport'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transport-list'
    | '/trash'
    | '/user-management'
    | '/api/keepalive'
    | '/memo/$id'
    | '/transport-edit/$id'
    | '/transport/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ConsigneesRoute: typeof ConsigneesRoute
  FleetRoute: typeof FleetRoute
  NewMemoRoute: typeof NewMemoRoute
  NewTransportRoute: typeof NewTransportRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TransportListRoute: typeof TransportListRoute
  TrashRoute: typeof TrashRoute
  UserManagementRoute: typeof UserManagementRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  MemoIdRoute: typeof MemoIdRoute
  TransportEditIdRoute: typeof TransportEditIdRoute
  TransportIdRoute: typeof TransportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-list': {
      id: '/transport-list'
      path: '/transport-list'
      fullPath: '/transport-list'
      preLoaderRoute: typeof TransportListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-transport': {
      id: '/new-transport'
      path: '/new-transport'
      fullPath: '/new-transport'
      preLoaderRoute: typeof NewTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-memo': {
      id: '/new-memo'
      path: '/new-memo'
      fullPath: '/new-memo'
      preLoaderRoute: typeof NewMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignees': {
      id: '/consignees'
      path: '/consignees'
      fullPath: '/consignees'
      preLoaderRoute: typeof ConsigneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/$id': {
      id: '/transport/$id'
      path: '/transport/$id'
      fullPath: '/transport/$id'
      preLoaderRoute: typeof TransportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-edit/$id': {
      id: '/transport-edit/$id'
      path: '/transport-edit/$id'
      fullPath: '/transport-edit/$id'
      preLoaderRoute: typeof TransportEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo/$id': {
      id: '/memo/$id'
      path: '/memo/$id'
      fullPath: '/memo/$id'
      preLoaderRoute: typeof MemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ConsigneesRoute: ConsigneesRoute,
  FleetRoute: FleetRoute,
  NewMemoRoute: NewMemoRoute,
  NewTransportRoute: NewTransportRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TransportListRoute: TransportListRoute,
  TrashRoute: TrashRoute,
  UserManagementRoute: UserManagementRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  MemoIdRoute: MemoIdRoute,
  TransportEditIdRoute: TransportEditIdRoute,
  TransportIdRoute: TransportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
